version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  fiber: &fiber
    build:
      context: ../.
      dockerfile: docker/go.Dockerfile
    container_name: fibler
    env_file:
      - ../.env
    depends_on:
      - postgres
    ports:
      - 5000:5000
    

  postgres:
    image: postgres:14.1
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ../.env
    ports:
      - 5432:5432
