// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/STEEDUj2kb/platform/ent/dailygaol"
	"github.com/STEEDUj2kb/platform/ent/predicate"
	"github.com/STEEDUj2kb/platform/ent/study"
	"github.com/STEEDUj2kb/platform/ent/weeklygaol"
)

// WeeklyGaolQuery is the builder for querying WeeklyGaol entities.
type WeeklyGaolQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WeeklyGaol
	// eager-loading edges.
	withDgaols *DailyGaolQuery
	withStudy  *StudyQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WeeklyGaolQuery builder.
func (wgq *WeeklyGaolQuery) Where(ps ...predicate.WeeklyGaol) *WeeklyGaolQuery {
	wgq.predicates = append(wgq.predicates, ps...)
	return wgq
}

// Limit adds a limit step to the query.
func (wgq *WeeklyGaolQuery) Limit(limit int) *WeeklyGaolQuery {
	wgq.limit = &limit
	return wgq
}

// Offset adds an offset step to the query.
func (wgq *WeeklyGaolQuery) Offset(offset int) *WeeklyGaolQuery {
	wgq.offset = &offset
	return wgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wgq *WeeklyGaolQuery) Unique(unique bool) *WeeklyGaolQuery {
	wgq.unique = &unique
	return wgq
}

// Order adds an order step to the query.
func (wgq *WeeklyGaolQuery) Order(o ...OrderFunc) *WeeklyGaolQuery {
	wgq.order = append(wgq.order, o...)
	return wgq
}

// QueryDgaols chains the current query on the "dgaols" edge.
func (wgq *WeeklyGaolQuery) QueryDgaols() *DailyGaolQuery {
	query := &DailyGaolQuery{config: wgq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(weeklygaol.Table, weeklygaol.FieldID, selector),
			sqlgraph.To(dailygaol.Table, dailygaol.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, weeklygaol.DgaolsTable, weeklygaol.DgaolsColumn),
		)
		fromU = sqlgraph.SetNeighbors(wgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStudy chains the current query on the "study" edge.
func (wgq *WeeklyGaolQuery) QueryStudy() *StudyQuery {
	query := &StudyQuery{config: wgq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(weeklygaol.Table, weeklygaol.FieldID, selector),
			sqlgraph.To(study.Table, study.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, weeklygaol.StudyTable, weeklygaol.StudyColumn),
		)
		fromU = sqlgraph.SetNeighbors(wgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WeeklyGaol entity from the query.
// Returns a *NotFoundError when no WeeklyGaol was found.
func (wgq *WeeklyGaolQuery) First(ctx context.Context) (*WeeklyGaol, error) {
	nodes, err := wgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{weeklygaol.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) FirstX(ctx context.Context) *WeeklyGaol {
	node, err := wgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WeeklyGaol ID from the query.
// Returns a *NotFoundError when no WeeklyGaol ID was found.
func (wgq *WeeklyGaolQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{weeklygaol.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) FirstIDX(ctx context.Context) int {
	id, err := wgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WeeklyGaol entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one WeeklyGaol entity is not found.
// Returns a *NotFoundError when no WeeklyGaol entities are found.
func (wgq *WeeklyGaolQuery) Only(ctx context.Context) (*WeeklyGaol, error) {
	nodes, err := wgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{weeklygaol.Label}
	default:
		return nil, &NotSingularError{weeklygaol.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) OnlyX(ctx context.Context) *WeeklyGaol {
	node, err := wgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WeeklyGaol ID in the query.
// Returns a *NotSingularError when exactly one WeeklyGaol ID is not found.
// Returns a *NotFoundError when no entities are found.
func (wgq *WeeklyGaolQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = &NotSingularError{weeklygaol.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) OnlyIDX(ctx context.Context) int {
	id, err := wgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WeeklyGaols.
func (wgq *WeeklyGaolQuery) All(ctx context.Context) ([]*WeeklyGaol, error) {
	if err := wgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return wgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) AllX(ctx context.Context) []*WeeklyGaol {
	nodes, err := wgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WeeklyGaol IDs.
func (wgq *WeeklyGaolQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := wgq.Select(weeklygaol.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) IDsX(ctx context.Context) []int {
	ids, err := wgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wgq *WeeklyGaolQuery) Count(ctx context.Context) (int, error) {
	if err := wgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return wgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) CountX(ctx context.Context) int {
	count, err := wgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wgq *WeeklyGaolQuery) Exist(ctx context.Context) (bool, error) {
	if err := wgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return wgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (wgq *WeeklyGaolQuery) ExistX(ctx context.Context) bool {
	exist, err := wgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WeeklyGaolQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wgq *WeeklyGaolQuery) Clone() *WeeklyGaolQuery {
	if wgq == nil {
		return nil
	}
	return &WeeklyGaolQuery{
		config:     wgq.config,
		limit:      wgq.limit,
		offset:     wgq.offset,
		order:      append([]OrderFunc{}, wgq.order...),
		predicates: append([]predicate.WeeklyGaol{}, wgq.predicates...),
		withDgaols: wgq.withDgaols.Clone(),
		withStudy:  wgq.withStudy.Clone(),
		// clone intermediate query.
		sql:  wgq.sql.Clone(),
		path: wgq.path,
	}
}

// WithDgaols tells the query-builder to eager-load the nodes that are connected to
// the "dgaols" edge. The optional arguments are used to configure the query builder of the edge.
func (wgq *WeeklyGaolQuery) WithDgaols(opts ...func(*DailyGaolQuery)) *WeeklyGaolQuery {
	query := &DailyGaolQuery{config: wgq.config}
	for _, opt := range opts {
		opt(query)
	}
	wgq.withDgaols = query
	return wgq
}

// WithStudy tells the query-builder to eager-load the nodes that are connected to
// the "study" edge. The optional arguments are used to configure the query builder of the edge.
func (wgq *WeeklyGaolQuery) WithStudy(opts ...func(*StudyQuery)) *WeeklyGaolQuery {
	query := &StudyQuery{config: wgq.config}
	for _, opt := range opts {
		opt(query)
	}
	wgq.withStudy = query
	return wgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Goal string `json:"goal,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WeeklyGaol.Query().
//		GroupBy(weeklygaol.FieldGoal).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (wgq *WeeklyGaolQuery) GroupBy(field string, fields ...string) *WeeklyGaolGroupBy {
	group := &WeeklyGaolGroupBy{config: wgq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := wgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return wgq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Goal string `json:"goal,omitempty"`
//	}
//
//	client.WeeklyGaol.Query().
//		Select(weeklygaol.FieldGoal).
//		Scan(ctx, &v)
//
func (wgq *WeeklyGaolQuery) Select(fields ...string) *WeeklyGaolSelect {
	wgq.fields = append(wgq.fields, fields...)
	return &WeeklyGaolSelect{WeeklyGaolQuery: wgq}
}

func (wgq *WeeklyGaolQuery) prepareQuery(ctx context.Context) error {
	for _, f := range wgq.fields {
		if !weeklygaol.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wgq.path != nil {
		prev, err := wgq.path(ctx)
		if err != nil {
			return err
		}
		wgq.sql = prev
	}
	return nil
}

func (wgq *WeeklyGaolQuery) sqlAll(ctx context.Context) ([]*WeeklyGaol, error) {
	var (
		nodes       = []*WeeklyGaol{}
		withFKs     = wgq.withFKs
		_spec       = wgq.querySpec()
		loadedTypes = [2]bool{
			wgq.withDgaols != nil,
			wgq.withStudy != nil,
		}
	)
	if wgq.withStudy != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, weeklygaol.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &WeeklyGaol{config: wgq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, wgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := wgq.withDgaols; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*WeeklyGaol)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Dgaols = []*DailyGaol{}
		}
		query.withFKs = true
		query.Where(predicate.DailyGaol(func(s *sql.Selector) {
			s.Where(sql.InValues(weeklygaol.DgaolsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.weekly_gaol_dgaols
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "weekly_gaol_dgaols" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "weekly_gaol_dgaols" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Dgaols = append(node.Edges.Dgaols, n)
		}
	}

	if query := wgq.withStudy; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*WeeklyGaol)
		for i := range nodes {
			if nodes[i].study_wgoals == nil {
				continue
			}
			fk := *nodes[i].study_wgoals
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(study.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "study_wgoals" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Study = n
			}
		}
	}

	return nodes, nil
}

func (wgq *WeeklyGaolQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wgq.querySpec()
	return sqlgraph.CountNodes(ctx, wgq.driver, _spec)
}

func (wgq *WeeklyGaolQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := wgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (wgq *WeeklyGaolQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   weeklygaol.Table,
			Columns: weeklygaol.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: weeklygaol.FieldID,
			},
		},
		From:   wgq.sql,
		Unique: true,
	}
	if unique := wgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := wgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, weeklygaol.FieldID)
		for i := range fields {
			if fields[i] != weeklygaol.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wgq *WeeklyGaolQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wgq.driver.Dialect())
	t1 := builder.Table(weeklygaol.Table)
	columns := wgq.fields
	if len(columns) == 0 {
		columns = weeklygaol.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wgq.sql != nil {
		selector = wgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range wgq.predicates {
		p(selector)
	}
	for _, p := range wgq.order {
		p(selector)
	}
	if offset := wgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WeeklyGaolGroupBy is the group-by builder for WeeklyGaol entities.
type WeeklyGaolGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wggb *WeeklyGaolGroupBy) Aggregate(fns ...AggregateFunc) *WeeklyGaolGroupBy {
	wggb.fns = append(wggb.fns, fns...)
	return wggb
}

// Scan applies the group-by query and scans the result into the given value.
func (wggb *WeeklyGaolGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := wggb.path(ctx)
	if err != nil {
		return err
	}
	wggb.sql = query
	return wggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := wggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(wggb.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := wggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) StringsX(ctx context.Context) []string {
	v, err := wggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) StringX(ctx context.Context) string {
	v, err := wggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(wggb.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := wggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) IntsX(ctx context.Context) []int {
	v, err := wggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) IntX(ctx context.Context) int {
	v, err := wggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(wggb.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := wggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := wggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) Float64X(ctx context.Context) float64 {
	v, err := wggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(wggb.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := wggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := wggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wggb *WeeklyGaolGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wggb *WeeklyGaolGroupBy) BoolX(ctx context.Context) bool {
	v, err := wggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wggb *WeeklyGaolGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range wggb.fields {
		if !weeklygaol.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wggb *WeeklyGaolGroupBy) sqlQuery() *sql.Selector {
	selector := wggb.sql.Select()
	aggregation := make([]string, 0, len(wggb.fns))
	for _, fn := range wggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(wggb.fields)+len(wggb.fns))
		for _, f := range wggb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(wggb.fields...)...)
}

// WeeklyGaolSelect is the builder for selecting fields of WeeklyGaol entities.
type WeeklyGaolSelect struct {
	*WeeklyGaolQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (wgs *WeeklyGaolSelect) Scan(ctx context.Context, v interface{}) error {
	if err := wgs.prepareQuery(ctx); err != nil {
		return err
	}
	wgs.sql = wgs.WeeklyGaolQuery.sqlQuery(ctx)
	return wgs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) ScanX(ctx context.Context, v interface{}) {
	if err := wgs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) Strings(ctx context.Context) ([]string, error) {
	if len(wgs.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := wgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) StringsX(ctx context.Context) []string {
	v, err := wgs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wgs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) StringX(ctx context.Context) string {
	v, err := wgs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) Ints(ctx context.Context) ([]int, error) {
	if len(wgs.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := wgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) IntsX(ctx context.Context) []int {
	v, err := wgs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wgs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) IntX(ctx context.Context) int {
	v, err := wgs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(wgs.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := wgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) Float64sX(ctx context.Context) []float64 {
	v, err := wgs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wgs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) Float64X(ctx context.Context) float64 {
	v, err := wgs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(wgs.fields) > 1 {
		return nil, errors.New("ent: WeeklyGaolSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := wgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) BoolsX(ctx context.Context) []bool {
	v, err := wgs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (wgs *WeeklyGaolSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wgs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{weeklygaol.Label}
	default:
		err = fmt.Errorf("ent: WeeklyGaolSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wgs *WeeklyGaolSelect) BoolX(ctx context.Context) bool {
	v, err := wgs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wgs *WeeklyGaolSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := wgs.sql.Query()
	if err := wgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
