// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DailyGaol is the predicate function for dailygaol builders.
type DailyGaol func(*sql.Selector)

// Study is the predicate function for study builders.
type Study func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WeeklyGaol is the predicate function for weeklygaol builders.
type WeeklyGaol func(*sql.Selector)
